version: v1
uri_prefix: /api/v1 

# Starter

Lumen starter app is a bootstrap of a microservice api or to scale as a backend for any client.

# User [/user]

## Get the an example [GET /user]

To get an example response

+ Request (application/json)

    + Headers
    
            Authorization: Token ApiKey123
            
+ Response 200 (application/json)

        {
            "status": 200,
            "message": "Successfully fetched user data"
        }
        
+ Request (application/json)

    + Headers
    
            Authorization: Token WrongApiKey
            
+ Response 401 (application/json)

        {
            "status": 401,
            "message": "Invalid API Key"
        }

## Add a new trip [POST /user]

Adds a new user to the db.

+ Request (application/json)

    + Headers
    
            Authorization: Token ApiKey123
            
    + Body

            {
                "first_name": "Sam",
                "last_name": "Son",
                "number": "27848118111",
                "status": "enabled"
            }
            
+ Response 200 (application/json)

        {
            "status": 200,
            "message": "User added successfully",
            "data": {
                "user_id": "1",
                "links": [
                    {
                        "rel": "next",
                        "uri": "/api/v1/user/1"
                    }
                ]
            }
        }
        
+ Request (application/json)

    + Headers
    
            Authorization: Token WrongApiKey
            
    + Body

            {
                "first_name": "Sam",
                "last_name": "Son",
                "number": "27848118111",
                "status": "enabled"
            }
            
+ Response 401 (application/json)

        {
            "status": 401,
            "message": "Invalid API Key"
        }

+ Request (application/json)

    + Headers
    
            Authorization: Token ApiKey123
            
            
    + Body

            {
                "last_name": "Son",
                "number": "27848118111",
                "status": "enabled"
            }
            
+ Response 400 (application/json)

        {
            "status": 400,
            "message": "Missing required field (first_name)"
        }   
        
+ Request (application/json)

    + Headers

            Authorization: Token ApiKey123


    + Body

            {
                "number": "27848118111",
                "status": "enabled"
            }

+ Response 400 (application/json)

        {
            "status": 400,
            "message": "Missing required field (first_name, last_name)"
        }

+ Request (application/json)

    + Headers

            Authorization: Token ApiKey123

    + Body

            {
                "first_name": "Sam",
                "last_name": "Son",
                "status": "enabled"
                "number": "someBadNumber"
            }

+ Response 406 (application/json)

        {
            "status": 406,
            "message": "This number is not valid for the <REGION> region.",
            "data": {
                "required_format": "<required format for country>"
            }
        }